"""
src/utils/pipeline_state_manager.py

Generic persistent state manager for all project pipelines.

The same class can be used by:

    Data Pipeline
        PipelineStateManager("data_pipeline")

    Salary ML Pipeline
        PipelineStateManager("salary_ml")

    Future Forecasting Pipeline
        PipelineStateManager("forecasting_ml")

    Future NLP Pipeline
        PipelineStateManager("nlp_ml")

Responsibilities
----------------
This class:

1. Stores stage execution state.
2. Calculates deterministic fingerprints for configuration/data
   representations.
3. Determines whether a stage can be reused.
4. Stores output fingerprints.
5. Stores artifact locations.
6. Supports stage invalidation.
7. Persists state between Python processes.

This class DOES NOT execute pipeline components.

The orchestrator remains responsible for execution.
"""

from __future__ import annotations

import hashlib
import json
import os
import tempfile
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, Dict, Optional


# ============================================================================
# Constants
# ============================================================================

STATE_VERSION = "1.0"


# ============================================================================
# Stage State
# ============================================================================


@dataclass
class StageState:
    """
    Persistent state describing the last successful/failed execution
    of one pipeline stage.
    """

    stage_name: str

    # What entered the stage.
    input_fingerprint: str

    # Configuration/code-related fingerprint affecting the stage.
    config_fingerprint: str

    # What the stage produced.
    output_fingerprint: str

    # Expected values:
    #
    #   success
    #   failed
    status: str

    # Persisted files/directories generated by the stage.
    output_artifacts: Dict[str, str] = field(
        default_factory=dict
    )

    # Additional lineage/debug information.
    metadata: Dict[str, Any] = field(
        default_factory=dict
    )


# ============================================================================
# Pipeline State Manager
# ============================================================================


class PipelineStateManager:
    """
    Generic state manager shared by Data and ML pipelines.

    Parameters
    ----------
    pipeline_name:
        Logical name of the pipeline.

        Examples:
            "data_pipeline"
            "salary_ml"
            "forecasting_ml"
            "nlp_ml"

    state_dir:
        Directory where pipeline state files are stored.
    """

    def __init__(
        self,
        pipeline_name: str,
        state_dir: str | Path = "artifacts/pipeline_state",
    ) -> None:

        self.pipeline_name = self._validate_pipeline_name(
            pipeline_name
        )

        self.state_dir = Path(state_dir)

        self.state_dir.mkdir(
            parents=True,
            exist_ok=True,
        )

        self.state_file = (
            self.state_dir
            / f"{self.pipeline_name}_state.json"
        )

        self._state = self._load()

    # ======================================================================
    # Validation
    # ======================================================================

    @staticmethod
    def _validate_pipeline_name(
        pipeline_name: str,
    ) -> str:
        """
        Validate and normalize pipeline name.
        """

        if not isinstance(pipeline_name, str):
            raise TypeError(
                "pipeline_name must be a string."
            )

        normalized = pipeline_name.strip()

        if not normalized:
            raise ValueError(
                "pipeline_name must not be empty."
            )

        allowed = set(
            "abcdefghijklmnopqrstuvwxyz"
            "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
            "0123456789"
            "_-"
        )

        if not all(
            character in allowed
            for character in normalized
        ):
            raise ValueError(
                "pipeline_name may contain only "
                "letters, numbers, '_' and '-'."
            )

        return normalized

    # ======================================================================
    # State Persistence
    # ======================================================================

    def _default_state(self) -> Dict[str, Any]:
        """
        Return a clean initial state structure.
        """

        return {
            "state_version": STATE_VERSION,
            "pipeline_name": self.pipeline_name,
            "stages": {},
        }

    def _load(self) -> Dict[str, Any]:
        """
        Load persistent state.

        A missing or corrupted state file causes a clean state to be
        created. This is intentionally conservative: corrupted state
        must never result in unsafe artifact reuse.
        """

        if not self.state_file.exists():
            return self._default_state()

        try:

            with open(
                self.state_file,
                "r",
                encoding="utf-8",
            ) as file:

                state = json.load(file)

            if not isinstance(state, dict):
                return self._default_state()

            if not isinstance(
                state.get("stages"),
                dict,
            ):
                return self._default_state()

            return state

        except (
            json.JSONDecodeError,
            OSError,
            TypeError,
        ):

            return self._default_state()

    def _save(self) -> None:
        """
        Atomically persist state.

        A temporary file is written first and then replaced so that
        an interrupted write is less likely to leave a corrupt state file.
        """

        self.state_dir.mkdir(
            parents=True,
            exist_ok=True,
        )

        file_descriptor, temp_name = tempfile.mkstemp(
            prefix=f".{self.pipeline_name}_",
            suffix=".tmp",
            dir=self.state_dir,
            text=True,
        )

        try:

            with os.fdopen(
                file_descriptor,
                "w",
                encoding="utf-8",
            ) as file:

                json.dump(
                    self._state,
                    file,
                    indent=4,
                    sort_keys=True,
                    default=str,
                )

                file.flush()

                os.fsync(
                    file.fileno()
                )

            Path(temp_name).replace(
                self.state_file
            )

        except Exception:

            try:
                os.remove(temp_name)
            except OSError:
                pass

            raise

    # ======================================================================
    # Generic Fingerprinting
    # ======================================================================

    @staticmethod
    def fingerprint(
        value: Any,
    ) -> str:
        """
        Generate a deterministic SHA-256 fingerprint from a Python value.

        Suitable for:

            dictionaries
            lists
            tuples
            configuration objects converted to dictionaries
            strings
            numbers
            metadata

        This method fingerprints the REPRESENTATION of a value.

        For actual files use fingerprint_utils.hash_file().

        For directories use fingerprint_utils.hash_directory().
        """

        normalized = json.dumps(
            value,
            sort_keys=True,
            separators=(",", ":"),
            default=str,
        )

        return hashlib.sha256(
            normalized.encode("utf-8")
        ).hexdigest()

    @classmethod
    def combine_fingerprints(
        cls,
        *fingerprints: str,
    ) -> str:
        """
        Combine multiple fingerprints into one deterministic fingerprint.

        Example:

            data fingerprint
            +
            config fingerprint
            +
            code fingerprint

            ↓

            stage input fingerprint
        """

        return cls.fingerprint(
            list(fingerprints)
        )

    # ======================================================================
    # Stage Access
    # ======================================================================

    def get_stage_state(
        self,
        stage_name: str,
    ) -> Optional[StageState]:
        """
        Return persisted state for a stage.

        Returns None when the stage has never completed.
        """

        raw_state = self._state["stages"].get(
            stage_name
        )

        if raw_state is None:
            return None

        try:

            return StageState(
                **raw_state
            )

        except TypeError:

            # Invalid state should never be treated as reusable.
            return None

    # ======================================================================
    # Reuse Decision
    # ======================================================================

    def is_stage_reusable(
        self,
        stage_name: str,
        input_fingerprint: str,
        config_fingerprint: str,
        verify_artifacts: bool = True,
    ) -> bool:
        """
        Determine whether a previously executed stage can be reused.

        A stage is reusable only when:

            1. Previous state exists.
            2. Previous execution succeeded.
            3. Input fingerprint is unchanged.
            4. Configuration fingerprint is unchanged.
            5. Persisted artifacts still exist, when verification is enabled.
        """

        previous = self.get_stage_state(
            stage_name
        )

        if previous is None:
            return False

        if previous.status != "success":
            return False

        if (
            previous.input_fingerprint
            != input_fingerprint
        ):
            return False

        if (
            previous.config_fingerprint
            != config_fingerprint
        ):
            return False

        if verify_artifacts:

            if not self._artifacts_exist(
                previous.output_artifacts
            ):
                return False

        return True

    # ======================================================================
    # Artifact Verification
    # ======================================================================

    @staticmethod
    def _artifacts_exist(
        artifacts: Dict[str, str],
    ) -> bool:
        """
        Verify that recorded artifact paths still exist.

        Empty artifact dictionaries are allowed because some lightweight
        stages may not persist a physical artifact.
        """

        if not artifacts:
            return True

        for artifact_path in artifacts.values():

            if not artifact_path:
                return False

            if not Path(
                artifact_path
            ).exists():

                return False

        return True

    # ======================================================================
    # Output Fingerprint
    # ======================================================================

    def get_output_fingerprint(
        self,
        stage_name: str,
    ) -> Optional[str]:
        """
        Return the output fingerprint of a successful stage.
        """

        stage = self.get_stage_state(
            stage_name
        )

        if stage is None:
            return None

        if stage.status != "success":
            return None

        if not stage.output_fingerprint:
            return None

        return stage.output_fingerprint

    # ======================================================================
    # Artifact Information
    # ======================================================================

    def get_output_artifacts(
        self,
        stage_name: str,
    ) -> Dict[str, str]:
        """
        Return recorded artifact locations for a stage.
        """

        stage = self.get_stage_state(
            stage_name
        )

        if stage is None:
            return {}

        return dict(
            stage.output_artifacts
        )

    # ======================================================================
    # Record Success
    # ======================================================================

    def record_stage_success(
        self,
        stage_name: str,
        input_fingerprint: str,
        config_fingerprint: str,
        output_fingerprint: str,
        output_artifacts: Optional[
            Dict[str, str]
        ] = None,
        metadata: Optional[
            Dict[str, Any]
        ] = None,
    ) -> None:
        """
        Record a successful stage execution.
        """

        stage_state = StageState(
            stage_name=stage_name,
            input_fingerprint=input_fingerprint,
            config_fingerprint=config_fingerprint,
            output_fingerprint=output_fingerprint,
            status="success",
            output_artifacts=dict(
                output_artifacts or {}
            ),
            metadata=dict(
                metadata or {}
            ),
        )

        self._state["stages"][
            stage_name
        ] = asdict(stage_state)

        self._save()

    # ======================================================================
    # Record Failure
    # ======================================================================

    def record_stage_failure(
        self,
        stage_name: str,
        error: str,
        metadata: Optional[
            Dict[str, Any]
        ] = None,
    ) -> None:
        """
        Record a failed stage execution.

        A failed stage can never be reused until a future execution
        successfully records it again.
        """

        previous = self.get_stage_state(
            stage_name
        )

        stage_state = StageState(
            stage_name=stage_name,

            input_fingerprint=(
                previous.input_fingerprint
                if previous
                else ""
            ),

            config_fingerprint=(
                previous.config_fingerprint
                if previous
                else ""
            ),

            output_fingerprint=(
                previous.output_fingerprint
                if previous
                else ""
            ),

            status="failed",

            output_artifacts=(
                dict(
                    previous.output_artifacts
                )
                if previous
                else {}
            ),

            metadata={
                "error": error,
                **(metadata or {}),
            },
        )

        self._state["stages"][
            stage_name
        ] = asdict(stage_state)

        self._save()

    # ======================================================================
    # Invalidation
    # ======================================================================

    def invalidate_stage(
        self,
        stage_name: str,
    ) -> None:
        """
        Invalidate one stage.
        """

        self._state["stages"].pop(
            stage_name,
            None,
        )

        self._save()

    def invalidate_from(
        self,
        stage_name: str,
        stage_order: list[str],
    ) -> None:
        """
        Invalidate the specified stage and every downstream stage.

        Example:

            A → B → C → D

        invalidate_from("B")

            B, C, D are removed.
            A remains valid.
        """

        if stage_name not in stage_order:

            raise ValueError(
                f"Unknown stage '{stage_name}'. "
                f"Available stages: {stage_order}"
            )

        start_index = stage_order.index(
            stage_name
        )

        for stage in stage_order[
            start_index:
        ]:

            self._state["stages"].pop(
                stage,
                None,
            )

        self._save()

    # ======================================================================
    # Inspection
    # ======================================================================

    def list_stage_names(self) -> tuple[str, ...]:
        """
        Return all stages currently recorded.
        """

        return tuple(
            self._state["stages"].keys()
        )

    def get_all_states(
        self,
    ) -> Dict[str, StageState]:
        """
        Return all valid recorded stage states.
        """

        result: Dict[
            str,
            StageState,
        ] = {}

        for stage_name in self.list_stage_names():

            stage = self.get_stage_state(
                stage_name
            )

            if stage is not None:
                result[stage_name] = stage

        return result

    # ======================================================================
    # Reset
    # ======================================================================

    def clear(self) -> None:
        """
        Delete all recorded state for this pipeline.

        Does NOT delete actual pipeline artifacts.
        """

        self._state = self._default_state()

        self._save()